# Generated by Django 4.2.1 on 2023-08-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0003_alter_exposure2_asbestos_exposure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exposure2",
            name="asbestos_exposure",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
    ]
