# Generated by Django 4.2.3 on 2023-08-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0004_alter_exposure2_asbestos_exposure"),
    ]

    operations = [
        migrations.CreateModel(
            name="ct_scan_nodule_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodule_rank", models.TextField(default=1, max_length=20)),
                ("nodule_slice_num", models.TextField(max_length=20)),
                ("nodule_segment", models.TextField(max_length=20)),
                ("nodule_cad_found", models.TextField(max_length=20)),
                (
                    "nodule_location_selection",
                    models.TextField(
                        choices=[
                            ("RUL", "RUL"),
                            ("RML", "RML"),
                            ("RLL", "RLL"),
                            ("LUL", "LUL"),
                            ("LLL", "LLL"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "nodule_status",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("retro", "Retro"),
                            ("first seen", "First Seen"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_interval_change",
                    models.TextField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("smaller", "Smaller"),
                            ("density increased", "Density Increased"),
                            ("benign", "Benign"),
                            ("resolved", "Resolved"),
                            ("rescted", "Resected"),
                            ("growing", "Growing"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_type",
                    models.TextField(
                        choices=[
                            ("solid", "Solid"),
                            ("SSN", "SSN"),
                            ("GGO", "GGO"),
                            ("Calcified", "Calcified"),
                            ("PFN", "PFN"),
                            ("Cystic", "Cystic"),
                            ("N/A", "N/A"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_axis_long", models.TextField(max_length=20)),
                ("nodule_axis_short", models.TextField(max_length=20)),
                ("nodule_axis_mean", models.TextField(max_length=20)),
                ("nodule_axis_volume", models.TextField(max_length=20)),
                ("nodule_axis_density", models.TextField(max_length=20)),
                (
                    "nodule_axis_sd",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("nodule_ssn_long", models.TextField(max_length=20)),
                ("nodule_ssn_short", models.TextField(max_length=20)),
                (
                    "nodule_description",
                    models.TextField(
                        choices=[
                            ("well defined", "Well Defined"),
                            ("lobulated", "Lobulated"),
                            ("spiculated", "Spiculated"),
                            ("halo", "Halo-Like"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location",
                    models.TextField(
                        choices=[
                            ("parenchymal", "Parenchymal"),
                            ("subpleural", "Subpleural"),
                            ("fissural", "Fissural"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_change_avediam", models.TextField(max_length=20)),
                ("nodule_change_dd", models.TextField(max_length=20)),
                ("nodule_change_volume", models.TextField(max_length=20)),
                ("nodule_change_volsperc", models.TextField(max_length=20)),
                ("nodule_change_mean", models.TextField(max_length=20)),
                ("nodule_comments", models.TextField(max_length=20)),
                ("nodule_risk_index", models.TextField(max_length=20)),
                ("nodule_key_nodule", models.TextField(max_length=20)),
                ("nodule_cancer_confirmed", models.TextField(max_length=20)),
                (
                    "nodule_recommended_fu",
                    models.TextField(
                        choices=[
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("12 Months", "12 Months"),
                            ("24 Months", "24 Months"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_fleicher_fu",
                    models.TextField(
                        choices=[
                            ("No Routine Follow-up", "No Routine Follow-up"),
                            ("3-6 Month Follow-up", "3-6 Month Follow-up"),
                            ("6-12 Month Follow-up", "6-12 Month Follow-up"),
                            ("12 Month Follow-up", "12 Month Follow-up"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_orders", models.TextField(max_length=100)),
                (
                    "nodule_status_cad",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("retro", "Retro"),
                            ("first seen", "First Seen"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location_selection_cad",
                    models.TextField(
                        choices=[
                            ("RUL", "RUL"),
                            ("RML", "RML"),
                            ("RLL", "RLL"),
                            ("LUL", "LUL"),
                            ("LLL", "LLL"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "nodule_interval_change_cad",
                    models.TextField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("smaller", "Smaller"),
                            ("density increased", "Density Increased"),
                            ("benign", "Benign"),
                            ("resolved", "Resolved"),
                            ("rescted", "Resected"),
                            ("growing", "Growing"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_type_cad",
                    models.TextField(
                        choices=[
                            ("solid", "Solid"),
                            ("SSN", "SSN"),
                            ("GGO", "GGO"),
                            ("Calcified", "Calcified"),
                            ("PFN", "PFN"),
                            ("Cystic", "Cystic"),
                            ("N/A", "N/A"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_axis_long_cad", models.TextField(max_length=20)),
                ("nodule_axis_short_cad", models.TextField(max_length=20)),
                ("nodule_axis_mean_cad", models.TextField(max_length=20)),
                ("nodule_axis_volume_cad", models.TextField(max_length=20)),
                ("nodule_axis_density_cad", models.TextField(max_length=20)),
                (
                    "nodule_axis_sd_cad",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("nodule_ssn_long_cad", models.TextField(max_length=20)),
                ("nodule_ssn_short_cad", models.TextField(max_length=20)),
                (
                    "nodule_description_cad",
                    models.TextField(
                        choices=[
                            ("well defined", "Well Defined"),
                            ("lobulated", "Lobulated"),
                            ("spiculated", "Spiculated"),
                            ("halo", "Halo-Like"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location_cad",
                    models.TextField(
                        choices=[
                            ("parenchymal", "Parenchymal"),
                            ("subpleural", "Subpleural"),
                            ("fissural", "Fissural"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_change_avediam_cad", models.TextField(max_length=20)),
                ("nodule_change_dd_cad", models.TextField(max_length=20)),
                ("nodule_change_volume_cad", models.TextField(max_length=20)),
                ("nodule_change_volsperc_cad", models.TextField(max_length=20)),
                ("nodule_change_mean_cad", models.TextField(max_length=20)),
                ("nodule_comments_cad", models.TextField(max_length=20)),
                ("nodule_risk_index_cad", models.TextField(max_length=20)),
                ("nodule_key_nodule_cad", models.TextField(max_length=20)),
                ("nodule_cancer_confirmed_cad", models.TextField(max_length=20)),
                (
                    "nodule_recommended_fu_cad",
                    models.TextField(
                        choices=[
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("12 Months", "12 Months"),
                            ("24 Months", "24 Months"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_fleicher_fu_cad",
                    models.TextField(
                        choices=[
                            ("No Routine Follow-up", "No Routine Follow-up"),
                            ("3-6 Month Follow-up", "3-6 Month Follow-up"),
                            ("6-12 Month Follow-up", "6-12 Month Follow-up"),
                            ("12 Month Follow-up", "12 Month Follow-up"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_orders_cad", models.TextField(max_length=100)),
                (
                    "participant_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataEntry.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ct_scan_nodule_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodule_rank", models.TextField(default=2, max_length=20)),
                ("nodule_slice_num", models.TextField(max_length=20)),
                ("nodule_segment", models.TextField(max_length=20)),
                ("nodule_cad_found", models.TextField(max_length=20)),
                (
                    "nodule_location_selection",
                    models.TextField(
                        choices=[
                            ("RUL", "RUL"),
                            ("RML", "RML"),
                            ("RLL", "RLL"),
                            ("LUL", "LUL"),
                            ("LLL", "LLL"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "nodule_status",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("retro", "Retro"),
                            ("first seen", "First Seen"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_interval_change",
                    models.TextField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("smaller", "Smaller"),
                            ("density increased", "Density Increased"),
                            ("benign", "Benign"),
                            ("resolved", "Resolved"),
                            ("rescted", "Resected"),
                            ("growing", "Growing"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_type",
                    models.TextField(
                        choices=[
                            ("solid", "Solid"),
                            ("SSN", "SSN"),
                            ("GGO", "GGO"),
                            ("Calcified", "Calcified"),
                            ("PFN", "PFN"),
                            ("Cystic", "Cystic"),
                            ("N/A", "N/A"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_axis_long", models.TextField(max_length=20)),
                ("nodule_axis_short", models.TextField(max_length=20)),
                ("nodule_axis_mean", models.TextField(max_length=20)),
                ("nodule_axis_volume", models.TextField(max_length=20)),
                ("nodule_axis_density", models.TextField(max_length=20)),
                (
                    "nodule_axis_sd",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("nodule_ssn_long", models.TextField(max_length=20)),
                ("nodule_ssn_short", models.TextField(max_length=20)),
                (
                    "nodule_description",
                    models.TextField(
                        choices=[
                            ("well defined", "Well Defined"),
                            ("lobulated", "Lobulated"),
                            ("spiculated", "Spiculated"),
                            ("halo", "Halo-Like"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location",
                    models.TextField(
                        choices=[
                            ("parenchymal", "Parenchymal"),
                            ("subpleural", "Subpleural"),
                            ("fissural", "Fissural"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_change_avediam", models.TextField(max_length=20)),
                ("nodule_change_dd", models.TextField(max_length=20)),
                ("nodule_change_volume", models.TextField(max_length=20)),
                ("nodule_change_volsperc", models.TextField(max_length=20)),
                ("nodule_change_mean", models.TextField(max_length=20)),
                ("nodule_comments", models.TextField(max_length=20)),
                ("nodule_risk_index", models.TextField(max_length=20)),
                ("nodule_key_nodule", models.TextField(max_length=20)),
                ("nodule_cancer_confirmed", models.TextField(max_length=20)),
                (
                    "nodule_recommended_fu",
                    models.TextField(
                        choices=[
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("12 Months", "12 Months"),
                            ("24 Months", "24 Months"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_fleicher_fu",
                    models.TextField(
                        choices=[
                            ("No Routine Follow-up", "No Routine Follow-up"),
                            ("3-6 Month Follow-up", "3-6 Month Follow-up"),
                            ("6-12 Month Follow-up", "6-12 Month Follow-up"),
                            ("12 Month Follow-up", "12 Month Follow-up"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_orders", models.TextField(max_length=100)),
                (
                    "nodule_status_cad",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("retro", "Retro"),
                            ("first seen", "First Seen"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location_selection_cad",
                    models.TextField(
                        choices=[
                            ("RUL", "RUL"),
                            ("RML", "RML"),
                            ("RLL", "RLL"),
                            ("LUL", "LUL"),
                            ("LLL", "LLL"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "nodule_interval_change_cad",
                    models.TextField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("smaller", "Smaller"),
                            ("density increased", "Density Increased"),
                            ("benign", "Benign"),
                            ("resolved", "Resolved"),
                            ("rescted", "Resected"),
                            ("growing", "Growing"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_type_cad",
                    models.TextField(
                        choices=[
                            ("solid", "Solid"),
                            ("SSN", "SSN"),
                            ("GGO", "GGO"),
                            ("Calcified", "Calcified"),
                            ("PFN", "PFN"),
                            ("Cystic", "Cystic"),
                            ("N/A", "N/A"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_axis_long_cad", models.TextField(max_length=20)),
                ("nodule_axis_short_cad", models.TextField(max_length=20)),
                ("nodule_axis_mean_cad", models.TextField(max_length=20)),
                ("nodule_axis_volume_cad", models.TextField(max_length=20)),
                ("nodule_axis_density_cad", models.TextField(max_length=20)),
                (
                    "nodule_axis_sd_cad",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("nodule_ssn_long_cad", models.TextField(max_length=20)),
                ("nodule_ssn_short_cad", models.TextField(max_length=20)),
                (
                    "nodule_description_cad",
                    models.TextField(
                        choices=[
                            ("well defined", "Well Defined"),
                            ("lobulated", "Lobulated"),
                            ("spiculated", "Spiculated"),
                            ("halo", "Halo-Like"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location_cad",
                    models.TextField(
                        choices=[
                            ("parenchymal", "Parenchymal"),
                            ("subpleural", "Subpleural"),
                            ("fissural", "Fissural"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_change_avediam_cad", models.TextField(max_length=20)),
                ("nodule_change_dd_cad", models.TextField(max_length=20)),
                ("nodule_change_volume_cad", models.TextField(max_length=20)),
                ("nodule_change_volsperc_cad", models.TextField(max_length=20)),
                ("nodule_change_mean_cad", models.TextField(max_length=20)),
                ("nodule_comments_cad", models.TextField(max_length=20)),
                ("nodule_risk_index_cad", models.TextField(max_length=20)),
                ("nodule_key_nodule_cad", models.TextField(max_length=20)),
                ("nodule_cancer_confirmed_cad", models.TextField(max_length=20)),
                (
                    "nodule_recommended_fu_cad",
                    models.TextField(
                        choices=[
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("12 Months", "12 Months"),
                            ("24 Months", "24 Months"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_fleicher_fu_cad",
                    models.TextField(
                        choices=[
                            ("No Routine Follow-up", "No Routine Follow-up"),
                            ("3-6 Month Follow-up", "3-6 Month Follow-up"),
                            ("6-12 Month Follow-up", "6-12 Month Follow-up"),
                            ("12 Month Follow-up", "12 Month Follow-up"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_orders_cad", models.TextField(max_length=100)),
                (
                    "participant_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataEntry.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ct_scan_nodule_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodule_rank", models.TextField(default=3, max_length=20)),
                ("nodule_slice_num", models.TextField(max_length=20)),
                ("nodule_segment", models.TextField(max_length=20)),
                ("nodule_cad_found", models.TextField(max_length=20)),
                (
                    "nodule_location_selection",
                    models.TextField(
                        choices=[
                            ("RUL", "RUL"),
                            ("RML", "RML"),
                            ("RLL", "RLL"),
                            ("LUL", "LUL"),
                            ("LLL", "LLL"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "nodule_status",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("retro", "Retro"),
                            ("first seen", "First Seen"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_interval_change",
                    models.TextField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("smaller", "Smaller"),
                            ("density increased", "Density Increased"),
                            ("benign", "Benign"),
                            ("resolved", "Resolved"),
                            ("rescted", "Resected"),
                            ("growing", "Growing"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_type",
                    models.TextField(
                        choices=[
                            ("solid", "Solid"),
                            ("SSN", "SSN"),
                            ("GGO", "GGO"),
                            ("Calcified", "Calcified"),
                            ("PFN", "PFN"),
                            ("Cystic", "Cystic"),
                            ("N/A", "N/A"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_axis_long", models.TextField(max_length=20)),
                ("nodule_axis_short", models.TextField(max_length=20)),
                ("nodule_axis_mean", models.TextField(max_length=20)),
                ("nodule_axis_volume", models.TextField(max_length=20)),
                ("nodule_axis_density", models.TextField(max_length=20)),
                (
                    "nodule_axis_sd",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("nodule_ssn_long", models.TextField(max_length=20)),
                ("nodule_ssn_short", models.TextField(max_length=20)),
                (
                    "nodule_description",
                    models.TextField(
                        choices=[
                            ("well defined", "Well Defined"),
                            ("lobulated", "Lobulated"),
                            ("spiculated", "Spiculated"),
                            ("halo", "Halo-Like"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location",
                    models.TextField(
                        choices=[
                            ("parenchymal", "Parenchymal"),
                            ("subpleural", "Subpleural"),
                            ("fissural", "Fissural"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_change_avediam", models.TextField(max_length=20)),
                ("nodule_change_dd", models.TextField(max_length=20)),
                ("nodule_change_volume", models.TextField(max_length=20)),
                ("nodule_change_volsperc", models.TextField(max_length=20)),
                ("nodule_change_mean", models.TextField(max_length=20)),
                ("nodule_comments", models.TextField(max_length=20)),
                ("nodule_risk_index", models.TextField(max_length=20)),
                ("nodule_key_nodule", models.TextField(max_length=20)),
                ("nodule_cancer_confirmed", models.TextField(max_length=20)),
                (
                    "nodule_recommended_fu",
                    models.TextField(
                        choices=[
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("12 Months", "12 Months"),
                            ("24 Months", "24 Months"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_fleicher_fu",
                    models.TextField(
                        choices=[
                            ("No Routine Follow-up", "No Routine Follow-up"),
                            ("3-6 Month Follow-up", "3-6 Month Follow-up"),
                            ("6-12 Month Follow-up", "6-12 Month Follow-up"),
                            ("12 Month Follow-up", "12 Month Follow-up"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_orders", models.TextField(max_length=100)),
                (
                    "nodule_status_cad",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("retro", "Retro"),
                            ("first seen", "First Seen"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location_selection_cad",
                    models.TextField(
                        choices=[
                            ("RUL", "RUL"),
                            ("RML", "RML"),
                            ("RLL", "RLL"),
                            ("LUL", "LUL"),
                            ("LLL", "LLL"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "nodule_interval_change_cad",
                    models.TextField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("smaller", "Smaller"),
                            ("density increased", "Density Increased"),
                            ("benign", "Benign"),
                            ("resolved", "Resolved"),
                            ("rescted", "Resected"),
                            ("growing", "Growing"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_type_cad",
                    models.TextField(
                        choices=[
                            ("solid", "Solid"),
                            ("SSN", "SSN"),
                            ("GGO", "GGO"),
                            ("Calcified", "Calcified"),
                            ("PFN", "PFN"),
                            ("Cystic", "Cystic"),
                            ("N/A", "N/A"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_axis_long_cad", models.TextField(max_length=20)),
                ("nodule_axis_short_cad", models.TextField(max_length=20)),
                ("nodule_axis_mean_cad", models.TextField(max_length=20)),
                ("nodule_axis_volume_cad", models.TextField(max_length=20)),
                ("nodule_axis_density_cad", models.TextField(max_length=20)),
                (
                    "nodule_axis_sd_cad",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("nodule_ssn_long_cad", models.TextField(max_length=20)),
                ("nodule_ssn_short_cad", models.TextField(max_length=20)),
                (
                    "nodule_description_cad",
                    models.TextField(
                        choices=[
                            ("well defined", "Well Defined"),
                            ("lobulated", "Lobulated"),
                            ("spiculated", "Spiculated"),
                            ("halo", "Halo-Like"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location_cad",
                    models.TextField(
                        choices=[
                            ("parenchymal", "Parenchymal"),
                            ("subpleural", "Subpleural"),
                            ("fissural", "Fissural"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_change_avediam_cad", models.TextField(max_length=20)),
                ("nodule_change_dd_cad", models.TextField(max_length=20)),
                ("nodule_change_volume_cad", models.TextField(max_length=20)),
                ("nodule_change_volsperc_cad", models.TextField(max_length=20)),
                ("nodule_change_mean_cad", models.TextField(max_length=20)),
                ("nodule_comments_cad", models.TextField(max_length=20)),
                ("nodule_risk_index_cad", models.TextField(max_length=20)),
                ("nodule_key_nodule_cad", models.TextField(max_length=20)),
                ("nodule_cancer_confirmed_cad", models.TextField(max_length=20)),
                (
                    "nodule_recommended_fu_cad",
                    models.TextField(
                        choices=[
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("12 Months", "12 Months"),
                            ("24 Months", "24 Months"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_fleicher_fu_cad",
                    models.TextField(
                        choices=[
                            ("No Routine Follow-up", "No Routine Follow-up"),
                            ("3-6 Month Follow-up", "3-6 Month Follow-up"),
                            ("6-12 Month Follow-up", "6-12 Month Follow-up"),
                            ("12 Month Follow-up", "12 Month Follow-up"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_orders_cad", models.TextField(max_length=100)),
                (
                    "participant_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataEntry.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ct_scan_nodule_4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodule_rank", models.TextField(default=4, max_length=20)),
                ("nodule_slice_num", models.TextField(max_length=20)),
                ("nodule_segment", models.TextField(max_length=20)),
                ("nodule_cad_found", models.TextField(max_length=20)),
                (
                    "nodule_location_selection",
                    models.TextField(
                        choices=[
                            ("RUL", "RUL"),
                            ("RML", "RML"),
                            ("RLL", "RLL"),
                            ("LUL", "LUL"),
                            ("LLL", "LLL"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "nodule_status",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("retro", "Retro"),
                            ("first seen", "First Seen"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_interval_change",
                    models.TextField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("smaller", "Smaller"),
                            ("density increased", "Density Increased"),
                            ("benign", "Benign"),
                            ("resolved", "Resolved"),
                            ("rescted", "Resected"),
                            ("growing", "Growing"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_type",
                    models.TextField(
                        choices=[
                            ("solid", "Solid"),
                            ("SSN", "SSN"),
                            ("GGO", "GGO"),
                            ("Calcified", "Calcified"),
                            ("PFN", "PFN"),
                            ("Cystic", "Cystic"),
                            ("N/A", "N/A"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_axis_long", models.TextField(max_length=20)),
                ("nodule_axis_short", models.TextField(max_length=20)),
                ("nodule_axis_mean", models.TextField(max_length=20)),
                ("nodule_axis_volume", models.TextField(max_length=20)),
                ("nodule_axis_density", models.TextField(max_length=20)),
                (
                    "nodule_axis_sd",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("nodule_ssn_long", models.TextField(max_length=20)),
                ("nodule_ssn_short", models.TextField(max_length=20)),
                (
                    "nodule_description",
                    models.TextField(
                        choices=[
                            ("well defined", "Well Defined"),
                            ("lobulated", "Lobulated"),
                            ("spiculated", "Spiculated"),
                            ("halo", "Halo-Like"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location",
                    models.TextField(
                        choices=[
                            ("parenchymal", "Parenchymal"),
                            ("subpleural", "Subpleural"),
                            ("fissural", "Fissural"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_change_avediam", models.TextField(max_length=20)),
                ("nodule_change_dd", models.TextField(max_length=20)),
                ("nodule_change_volume", models.TextField(max_length=20)),
                ("nodule_change_volsperc", models.TextField(max_length=20)),
                ("nodule_change_mean", models.TextField(max_length=20)),
                ("nodule_comments", models.TextField(max_length=20)),
                ("nodule_risk_index", models.TextField(max_length=20)),
                ("nodule_key_nodule", models.TextField(max_length=20)),
                ("nodule_cancer_confirmed", models.TextField(max_length=20)),
                (
                    "nodule_recommended_fu",
                    models.TextField(
                        choices=[
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("12 Months", "12 Months"),
                            ("24 Months", "24 Months"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_fleicher_fu",
                    models.TextField(
                        choices=[
                            ("No Routine Follow-up", "No Routine Follow-up"),
                            ("3-6 Month Follow-up", "3-6 Month Follow-up"),
                            ("6-12 Month Follow-up", "6-12 Month Follow-up"),
                            ("12 Month Follow-up", "12 Month Follow-up"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_orders", models.TextField(max_length=100)),
                (
                    "nodule_status_cad",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("retro", "Retro"),
                            ("first seen", "First Seen"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location_selection_cad",
                    models.TextField(
                        choices=[
                            ("RUL", "RUL"),
                            ("RML", "RML"),
                            ("RLL", "RLL"),
                            ("LUL", "LUL"),
                            ("LLL", "LLL"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "nodule_interval_change_cad",
                    models.TextField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("smaller", "Smaller"),
                            ("density increased", "Density Increased"),
                            ("benign", "Benign"),
                            ("resolved", "Resolved"),
                            ("rescted", "Resected"),
                            ("growing", "Growing"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_type_cad",
                    models.TextField(
                        choices=[
                            ("solid", "Solid"),
                            ("SSN", "SSN"),
                            ("GGO", "GGO"),
                            ("Calcified", "Calcified"),
                            ("PFN", "PFN"),
                            ("Cystic", "Cystic"),
                            ("N/A", "N/A"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_axis_long_cad", models.TextField(max_length=20)),
                ("nodule_axis_short_cad", models.TextField(max_length=20)),
                ("nodule_axis_mean_cad", models.TextField(max_length=20)),
                ("nodule_axis_volume_cad", models.TextField(max_length=20)),
                ("nodule_axis_density_cad", models.TextField(max_length=20)),
                (
                    "nodule_axis_sd_cad",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("nodule_ssn_long_cad", models.TextField(max_length=20)),
                ("nodule_ssn_short_cad", models.TextField(max_length=20)),
                (
                    "nodule_description_cad",
                    models.TextField(
                        choices=[
                            ("well defined", "Well Defined"),
                            ("lobulated", "Lobulated"),
                            ("spiculated", "Spiculated"),
                            ("halo", "Halo-Like"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location_cad",
                    models.TextField(
                        choices=[
                            ("parenchymal", "Parenchymal"),
                            ("subpleural", "Subpleural"),
                            ("fissural", "Fissural"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_change_avediam_cad", models.TextField(max_length=20)),
                ("nodule_change_dd_cad", models.TextField(max_length=20)),
                ("nodule_change_volume_cad", models.TextField(max_length=20)),
                ("nodule_change_volsperc_cad", models.TextField(max_length=20)),
                ("nodule_change_mean_cad", models.TextField(max_length=20)),
                ("nodule_comments_cad", models.TextField(max_length=20)),
                ("nodule_risk_index_cad", models.TextField(max_length=20)),
                ("nodule_key_nodule_cad", models.TextField(max_length=20)),
                ("nodule_cancer_confirmed_cad", models.TextField(max_length=20)),
                (
                    "nodule_recommended_fu_cad",
                    models.TextField(
                        choices=[
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("12 Months", "12 Months"),
                            ("24 Months", "24 Months"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_fleicher_fu_cad",
                    models.TextField(
                        choices=[
                            ("No Routine Follow-up", "No Routine Follow-up"),
                            ("3-6 Month Follow-up", "3-6 Month Follow-up"),
                            ("6-12 Month Follow-up", "6-12 Month Follow-up"),
                            ("12 Month Follow-up", "12 Month Follow-up"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_orders_cad", models.TextField(max_length=100)),
                (
                    "participant_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataEntry.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ct_scan_nodule_5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodule_rank", models.TextField(default=5, max_length=20)),
                ("nodule_slice_num", models.TextField(max_length=20)),
                ("nodule_segment", models.TextField(max_length=20)),
                ("nodule_cad_found", models.TextField(max_length=20)),
                (
                    "nodule_location_selection",
                    models.TextField(
                        choices=[
                            ("RUL", "RUL"),
                            ("RML", "RML"),
                            ("RLL", "RLL"),
                            ("LUL", "LUL"),
                            ("LLL", "LLL"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "nodule_status",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("retro", "Retro"),
                            ("first seen", "First Seen"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_interval_change",
                    models.TextField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("smaller", "Smaller"),
                            ("density increased", "Density Increased"),
                            ("benign", "Benign"),
                            ("resolved", "Resolved"),
                            ("rescted", "Resected"),
                            ("growing", "Growing"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_type",
                    models.TextField(
                        choices=[
                            ("solid", "Solid"),
                            ("SSN", "SSN"),
                            ("GGO", "GGO"),
                            ("Calcified", "Calcified"),
                            ("PFN", "PFN"),
                            ("Cystic", "Cystic"),
                            ("N/A", "N/A"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_axis_long", models.TextField(max_length=20)),
                ("nodule_axis_short", models.TextField(max_length=20)),
                ("nodule_axis_mean", models.TextField(max_length=20)),
                ("nodule_axis_volume", models.TextField(max_length=20)),
                ("nodule_axis_density", models.TextField(max_length=20)),
                (
                    "nodule_axis_sd",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("nodule_ssn_long", models.TextField(max_length=20)),
                ("nodule_ssn_short", models.TextField(max_length=20)),
                (
                    "nodule_description",
                    models.TextField(
                        choices=[
                            ("well defined", "Well Defined"),
                            ("lobulated", "Lobulated"),
                            ("spiculated", "Spiculated"),
                            ("halo", "Halo-Like"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location",
                    models.TextField(
                        choices=[
                            ("parenchymal", "Parenchymal"),
                            ("subpleural", "Subpleural"),
                            ("fissural", "Fissural"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_change_avediam", models.TextField(max_length=20)),
                ("nodule_change_dd", models.TextField(max_length=20)),
                ("nodule_change_volume", models.TextField(max_length=20)),
                ("nodule_change_volsperc", models.TextField(max_length=20)),
                ("nodule_change_mean", models.TextField(max_length=20)),
                ("nodule_comments", models.TextField(max_length=20)),
                ("nodule_risk_index", models.TextField(max_length=20)),
                ("nodule_key_nodule", models.TextField(max_length=20)),
                ("nodule_cancer_confirmed", models.TextField(max_length=20)),
                (
                    "nodule_recommended_fu",
                    models.TextField(
                        choices=[
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("12 Months", "12 Months"),
                            ("24 Months", "24 Months"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_fleicher_fu",
                    models.TextField(
                        choices=[
                            ("No Routine Follow-up", "No Routine Follow-up"),
                            ("3-6 Month Follow-up", "3-6 Month Follow-up"),
                            ("6-12 Month Follow-up", "6-12 Month Follow-up"),
                            ("12 Month Follow-up", "12 Month Follow-up"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_orders", models.TextField(max_length=100)),
                (
                    "nodule_status_cad",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("retro", "Retro"),
                            ("first seen", "First Seen"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location_selection_cad",
                    models.TextField(
                        choices=[
                            ("RUL", "RUL"),
                            ("RML", "RML"),
                            ("RLL", "RLL"),
                            ("LUL", "LUL"),
                            ("LLL", "LLL"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "nodule_interval_change_cad",
                    models.TextField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("smaller", "Smaller"),
                            ("density increased", "Density Increased"),
                            ("benign", "Benign"),
                            ("resolved", "Resolved"),
                            ("rescted", "Resected"),
                            ("growing", "Growing"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_type_cad",
                    models.TextField(
                        choices=[
                            ("solid", "Solid"),
                            ("SSN", "SSN"),
                            ("GGO", "GGO"),
                            ("Calcified", "Calcified"),
                            ("PFN", "PFN"),
                            ("Cystic", "Cystic"),
                            ("N/A", "N/A"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_axis_long_cad", models.TextField(max_length=20)),
                ("nodule_axis_short_cad", models.TextField(max_length=20)),
                ("nodule_axis_mean_cad", models.TextField(max_length=20)),
                ("nodule_axis_volume_cad", models.TextField(max_length=20)),
                ("nodule_axis_density_cad", models.TextField(max_length=20)),
                (
                    "nodule_axis_sd_cad",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("nodule_ssn_long_cad", models.TextField(max_length=20)),
                ("nodule_ssn_short_cad", models.TextField(max_length=20)),
                (
                    "nodule_description_cad",
                    models.TextField(
                        choices=[
                            ("well defined", "Well Defined"),
                            ("lobulated", "Lobulated"),
                            ("spiculated", "Spiculated"),
                            ("halo", "Halo-Like"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_location_cad",
                    models.TextField(
                        choices=[
                            ("parenchymal", "Parenchymal"),
                            ("subpleural", "Subpleural"),
                            ("fissural", "Fissural"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_change_avediam_cad", models.TextField(max_length=20)),
                ("nodule_change_dd_cad", models.TextField(max_length=20)),
                ("nodule_change_volume_cad", models.TextField(max_length=20)),
                ("nodule_change_volsperc_cad", models.TextField(max_length=20)),
                ("nodule_change_mean_cad", models.TextField(max_length=20)),
                ("nodule_comments_cad", models.TextField(max_length=20)),
                ("nodule_risk_index_cad", models.TextField(max_length=20)),
                ("nodule_key_nodule_cad", models.TextField(max_length=20)),
                ("nodule_cancer_confirmed_cad", models.TextField(max_length=20)),
                (
                    "nodule_recommended_fu_cad",
                    models.TextField(
                        choices=[
                            ("3 Months", "3 Months"),
                            ("6 Months", "6 Months"),
                            ("12 Months", "12 Months"),
                            ("24 Months", "24 Months"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "nodule_fleicher_fu_cad",
                    models.TextField(
                        choices=[
                            ("No Routine Follow-up", "No Routine Follow-up"),
                            ("3-6 Month Follow-up", "3-6 Month Follow-up"),
                            ("6-12 Month Follow-up", "6-12 Month Follow-up"),
                            ("12 Month Follow-up", "12 Month Follow-up"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("nodule_orders_cad", models.TextField(max_length=100)),
                (
                    "participant_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataEntry.participant",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="acheson",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="aluminum",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="arsenic",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="atsugi",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="beryllium",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="burn_pits",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="cadmium",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="chromium",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="coal",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="coke",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="diesel",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="ether",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="iron",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="mining",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="munitions",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="nickel",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="oil_fires",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="painting",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="plutonium",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="radiation",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="radon",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="rubber",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="sand_storms",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="silica_exposure",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="soot",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="sulfur",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="sulfur_fires",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="warfare",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exposure2",
            name="welding",
            field=models.TextField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Dont Know", "Dont Know")],
                default="No",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(name="ct_scan_nodules",),
    ]
