# Generated by Django 4.2.3 on 2023-08-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DataEntry",
            "0005_ct_scan_nodule_1_ct_scan_nodule_2_ct_scan_nodule_3_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_1",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_2",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_3",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_4",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_5",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_6",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_7",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_8",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_9",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_9_a",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_9_b",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_9_c",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_9_d",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
