# Generated by Django 4.2.3 on 2023-09-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0006_alter_inclusion_inclusion_criteria_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inclusion",
            name="consent_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("consented", "consented"),
                    ("not consented", "not consented"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_status",
            field=models.TextField(
                blank=True,
                choices=[
                    (
                        "eligible and willing to participate",
                        "eligible and willing to participate",
                    ),
                    (
                        "eligible but unwilling to participate",
                        "eligible but unwilling to participate",
                    ),
                    ("ineligible", "ineligible"),
                    (
                        "ineligible but willing to participate",
                        "ineligible but willing to participate",
                    ),
                ],
                max_length=80,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="screening_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("enrolled", "enrolled"),
                    ("pending interview", "pending interview"),
                    ("pending enrollment", "pending enrollment"),
                    ("ineligible", "ineligible"),
                    ("declined study", "declined study"),
                    ("off study", "off study"),
                    ("confirmed study", "confirmed study"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
