# Generated by Django 4.2.3 on 2023-09-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0007_alter_inclusion_consent_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatory_questionaire_fg",
            name="bronchodialators",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire_fg",
            name="inhaled_drugs",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire_fg",
            name="metformin",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire_fg",
            name="statins",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
